#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Thu Aug  1 14:36:46 2019

@author: yanghuiwang
"""

def get_noisy(ori_graph,percentage=0.05,verbose=False):
    random.seed(1)
    graph=ori_graph.copy()
    if(verbose==True):
        print("Before getting noisy, the world has",ori_graph.composite_adj.sum(), "edges")
    missing_edges={}
    channels=graph.ch_to_adj.keys()
    i_list = list(range(graph.n_nodes))
    j_list = list(range(graph.n_nodes))
    
    for channel in channels:
        np.random.shuffle(i_list)
        miss_edge=0
        adj=graph.ch_to_adj[channel]
        edge_count=adj.sum()
        threshold=percentage*edge_count
        if(threshold<1):
            continue
        print("edge_count",edge_count,"threshold",threshold)

        for i in i_list:
            if adj[i,:].sum==0:
                continue
            #try:
            np.random.shuffle(j_list)
            for j in j_list: # parametrize this number??
                if adj[i,j]==0:
                    continue
                adj[i,j]=adj[i,j]-1
                miss_edge+=1
                if(miss_edge>threshold):
                    break
            if(miss_edge>threshold):
                    break
        missing_edges[channel]=miss_edge
        print("miss_edge",miss_edge,"missing_edges",missing_edges)
        graph.ch_to_adj[channel]=adj
    if(verbose==True):
        print("After getting noisy, the world has",graph.composite_adj.sum() ,"edges")
    return graph
 
